### ISSUE TITLE
[Request] Any chance you might be willing to add OpenUPM support?

### ISSUE THREAD

**Issue by MostHated** [WooshiiDev/HierarchyDecorator#1]
Hey there,
This package looks great. (Honestly might end up being even better than some paid ones. 👍) Any chance you might be willing to add OpenUPM support? (https://openupm.com/). This definitely seems like it would quickly become one of the "every new project" type packages, and supporting OpenUPM makes it easier for folks to create new project initialization/ package installation scripts and such. 

Thanks,
-MH

**Comment by WooshiiDev** [comment]
> Hey there,
> This package looks great. (Honestly might end up being even better than some paid ones. 👍) Any chance you might be willing to add OpenUPM support? (https://openupm.com/). This definitely seems like it would quickly become one of the "every new project" type packages, and supporting OpenUPM makes it easier for folks to create new project initialization/ package installation scripts and such.
> 
> Thanks,
> -MH

Hello there MostHated,
I appreciate the kind words, and I hope this comes of good use to you!

I've just added OpenUPM support and it should be good to go 👍 
Thanks for the heads up for this as I never knew it existed prior \o.

**Comment by WooshiiDev** [comment]
Added requested feature

**Comment by MostHated** [comment]
Awesome news. I am sure that not only myself, but many others will appreciate it. 👍

(P.S. I realized after a while of playing around that under settings there was the option to enable alternating background colors, it just wasn't on by default. I am not sure of your thoughts on it, but I would have that on by default, it really adds a nice overall new depth to the hierarchy and a more premium feel out of the box, which I feel adds a lot to the "first impression", even when just looking at the images on the repo.)

**Comment by MostHated** [comment]
Sorry to revisit an old issue, but I just wanted to let you know I went to install the package using OpenUPM:

```
openupm add com.wooshii.hierarchydecorator
```

but ended up getting back the following error:

```
❯ openupm add com.wooshii.hierarchydecorator
[ERROR] package not found: com.wooshii.hierarchydecorator
```
I have used OpenUPN to install dozens of packages, but I can't say I ever remember seeing this error before. I am not sure if it is something on their side, or something here?

Were you able to successfully install it yourself yet using it?

**Comment by MostHated** [comment]
As I see the issue:

https://openupm.com/packages/com.wooshii.hierarchydecorator/

![](https://i.imgur.com/UTZGEOx.png)

It looks like the repo itself needs some tags and such to be picked up and used by OpenUPM. It looks like a whoollleee lot of repos that submitted theirself to the site need that as well, there are hundreds in "Pending" status for the same thing, lol.

https://openupm.com/docs/adding-upm-package.html#handling-a-repository-without-git-tag

**Comment by MostHated** [comment]
@WooshiiDev
