### ISSUE TITLE
Warning: No script asset for HierarchyPreferences. Check that the definition is in a file of the same name.

### ISSUE THREAD

**Issue by Thane5** [WooshiiDev/HierarchyDecorator#16]
I installed it via git URL and as a folder import, and this warning keeps appearing.

Tested in Unity 2020.2

**Comment by WooshiiDev** [comment]
Hello there Thane,

I've investigated this and attempted to reproduce this warning appearing, could you provide a screenshot? Is it coming from HierarchyDecorator's files?

Thanks

**Comment by Thane5** [comment]
I had this yesterday everytime i installed the plugin, even after restarting Unity. But it seems that after booting my PC up again today, its not there anymore.

**Comment by Thane5** [comment]
Okay the warning is back now...

It seems something funky is going on here, i also opened a project i havent touched in weeks, and the settings for Hierarchy Decorator apparently reset themselves. I'm not sure what to make out of this, but here you have a screenshot:

![Warning](https://user-images.githubusercontent.com/13683581/105852028-2f8ec500-5fe4-11eb-81bf-39311bb5a7e4.png)

**Comment by Thane5** [comment]
Here is a more detailled warning that just appeared in the same project
![Warning](https://user-images.githubusercontent.com/13683581/105988682-4d216480-60a0-11eb-8f97-35ae631500eb.png)

**Comment by WooshiiDev** [comment]
Hello @Thane5,

could I ask, is this the most recent version of HierarchyDecorator?

Currently, I'm reworking some of the systems, as I've been busy elsewhere and I've unfortunately had to leave work on this. So if there's any problems with the current versions I'll instantly get to fixing them.

This may be a problem to do with the AssetDatabase, but I'm curious what's causing it to happen.

**Comment by Thane5** [comment]
The package Manager says  0.4.6

**Comment by WooshiiDev** [comment]
Hmm that's quite interesting, I'll do some investigation and see if I can get this to reproduce. I did attempt yesterday on some blank projects, but I'll see what I can do. It may even be a meta file issue.

**Comment by Thane5** [comment]
My bad, turns out this was caused by another script that modifies the Hierarchy window.
