### ISSUE TITLE
Expand All / Collapse All overlaps text

### ISSUE THREAD

**Issue by Medallyon** [WooshiiDev/HierarchyDecorator#17]
![image](https://user-images.githubusercontent.com/17483199/128029884-e322f010-a593-472e-aaf6-0cbac30e1a46.png)

**Comment by WooshiiDev** [comment]
With the most [recent release](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/0.7.0.0) this should be fixed now. If this occurs again, please let me know and I'll investigate further, but it should not be an issue anymore.

Appreciate the reports on issues 👍
