### ISSUE TITLE
Expand/Collapse arrow is impossible to spot on selected transforms

### ISSUE THREAD

**Issue by Medallyon** [WooshiiDev/HierarchyDecorator#19]
![image](https://user-images.githubusercontent.com/17483199/128033201-b1a2ca51-b6f8-4539-91d2-967cb41fa75b.png)

**Comment by Medallyon** [comment]
Update: This only happens when the `Stretch Width` setting for the two-tone background is disabled.

**Comment by WooshiiDev** [comment]
Hey there, 

In the upcoming restructure, I've removed the stretch width. I think I originally added this in when I wasn't really thinking smart about how to handle drawing content. It's a useless feature to have unless specified widths could be assigned.

After the next release is  published all foldout/expand icon issues with two-tone or prefix styles should be fixed. I'll keep this open until then, just to make sure that it's all clear

**Comment by WooshiiDev** [comment]
[Hierarchy Decorator v0.7](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/0.7.0.0) has just been released with fixes to this issue 🙂
