### ISSUE TITLE
Bug: package.json version is not compatible with UPM

### ISSUE THREAD

**Issue by Medallyon** [WooshiiDev/HierarchyDecorator#27]
Unity Version
2020.3.0f1

```
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/wooshiidev/HierarchyDecorator.git]:
  Manifest [C:\Projects\learning_platform\Library\PackageCache\com.wooshii.hierarchydecorator@164cc81c3c\package.json] is invalid:
    Version '0.7.1.0' is invalid. Expected a 'SemVer' compatible value. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

**To Reproduce (If applicable)**
Attempt to install the package via `Unity > Window > Package Manager > Install via git`

**Comment by WooshiiDev** [comment]
Ah yeah SemVer is 3 digits rather than 4, I can update the version but the package.json updater action will need stopped for now.

**Comment by WooshiiDev** [comment]
Updated the package version and tested with UPM,

sorry again,
Wooshii

**Comment by Medallyon** [comment]
@WooshiiDev what happened to your discord account?
