### ISSUE TITLE
Errors when trying to create settings file on first import

### ISSUE THREAD

**Issue by SilentSin** [WooshiiDev/HierarchyDecorator#3]
In `HierarchyDecoratorSettings.cs` right below `//Quick fix for now to stop duplication issues` it needs to null check the `components`:

```
if (components != null && components.Count > allTypes.Length)
```

It should probably also just `Clear` the list instead of allocating a new one, but I haven't looked any further into it.

**Comment by WooshiiDev** [comment]
Hello there! Thanks for reporting this, helps me out a lot when I miss some things 😓 

This should be entirely fixed now,
I've had this issue for a week or so now and should have been sorted as soon as possible, including the fact someone else mentioned it to me.

Thanks again for the report on it, you have any other issues feel free to add another issue!
~ Wooshii \o.
