### ISSUE TITLE
Bug - Settings object reference not found

### ISSUE THREAD

**Issue by Vacui** [WooshiiDev/HierarchyDecorator#42]
**Current Unity version used**
2018.4.24f1

**Describe the bug**
After installing the plugin using the .unitypackage provided with the release 0.8.4, I found out that the script is unable to detect the ScriptableObject containing the Settings. A _NullRefereceException_ is printed in the console, originated on the _GetOrCreateSettings_ function.

**To Reproduce (If applicable)**
The plugin works perfectly fine in a 2018.4.24f1 project, therefore I'm not aware of a way to reproduce this problem.

**Screenshots**
![Screenshot 2021-10-14 at 08 44 15](https://user-images.githubusercontent.com/45497567/137265592-71911c49-12a3-413b-9566-0e411047dbcc.png)

**Additional context**
The project I'm working is big and complex, I can't exclude the possibility that this problem is originated by other scripts' behaviours.

**Comment by Vacui** [comment]
After testing the same problem on a clean project in 2018.4.24f1, and seeing the plugin working perfectly find,I can say the problem is originated from something in my own project.
I will try to uninstall the plugin again, and running a few more tests, to see if the problem persists.

I updated the original post removing the "reproduce" part.

**Comment by Vacui** [comment]
I found the culprit of the error.
When calling the method _AssetUtility.FindOrCreateScriptable_, the value passed as type name was "Settings", and I already had a class with that name in another namespace.
To fix the problem I changed the value of the constant _SETTINGS_TYPE_STRING_ in **HierarchyDecorator** from "Settings" to "HierarchyDecorator.Settings", to avoid the collision.

**Comment by Vacui** [comment]
It seems it is working for the time being, thx for the quick fix.

**Comment by WooshiiDev** [comment]
Ah fantastic, great to know it's been fixed. I'm sorry it's not on the main branch yet, other work has been busy, will be back on this soon 🙂

**Comment by WooshiiDev** [comment]
Hi Vacui, I've released a fix for this in [v0.8.5](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/v0.8.5). 
As this seems to be fixed, I'm going to close the issue, however if there's any further issues please feel free to reply to this issue and I'll reopen it 🙂
