### ISSUE TITLE
Feature Request - Activation Swiping

### ISSUE THREAD

**Issue by Razenpok** [WooshiiDev/HierarchyDecorator#43]
**Feature Description**
Another (now-archived) hierarchy-enchancing plugin [Smart Hierarchy](https://github.com/neon-age/Smart-Hierarchy) does a cool thing with activation checkbox which is activation swiping. Basically, dragging mouse across several checkboxes with LMB down bulk-toggles these checkboxes. You can read more about it [here](https://github.com/neon-age/Smart-Hierarchy/wiki/Activation-Toggle#swiping)

**Reason for feature**
It was really useful back when I was using that package.

By the way, there is a bunch of other cool features implemented in that plugin (like Hover Preview), so I recommend checking it out for inspiration (if you need one 😉)

**Comment by WooshiiDev** [comment]
Hey there Razen,

I think this is a brilliant idea and I encourage any ideas that have or haven't existed in other plugins 👏 I don't like directly copying features and I'd rather enhance or extend them if possible. 

In another feature request - #20 - multi-select on a much simpler form has been requested. After some things have been checked off the list I'll be doing some additional features to the hierarchy and these are the sort of features I'm totally on board for.

I've looked at Smart Hierc a little but not taken a deep dive as much as I'd have liked to. 

I'll keep this open and I'll pin this too as I think this is a really good addition 🙂 
Cheers for the request, appreciate it

**Comment by WooshiiDev** [comment]
I've implemented some basic activation swiping that also undo's nicely 🙂
I've been thinking of the different states that can come up like in Smart Hierarchy i.e. same active state, if any are selected, only toggle them etc.

I'm considering adding some form of direct multi-select toggle too, where you can directly toggle all after multi-selection.

Any thoughts?

![hd_activation_swiping_2](https://user-images.githubusercontent.com/31889435/150717607-7807ac0f-4f5e-4ec7-a7fb-79eec947c1ec.gif)

**Comment by WooshiiDev** [comment]
Selection only toggles - active state checks have been disabled in this one so all could be toggled

![hd_activation_swiping_3](https://user-images.githubusercontent.com/31889435/150740916-b0f8a3bb-b89e-4499-950c-faa78c6bc290.gif)

**Comment by WooshiiDev** [comment]
Depth-only toggling

![hd_active_swipe_depth](https://user-images.githubusercontent.com/31889435/150741325-bdf5a885-214d-4e19-be15-ac37e5e714f2.gif)

**Comment by Razenpok** [comment]
Hey WooshiiDev

> same active state
👍 

> Selection only toggles
👍 

> Depth-only toggling
👍

Looks good to me!

**Comment by WooshiiDev** [comment]
Been a while, but finished this feature, pushing to v0.9 soon 👏
