### ISSUE TITLE
Bug - Game Object name gets obstructed when it has a lot of components

### ISSUE THREAD

**Issue by Razenpok** [WooshiiDev/HierarchyDecorator#44]
**Current Unity version used**
2019.4.16f1

**Screenshots**
![image](https://user-images.githubusercontent.com/8434406/140917521-cceda980-1a6b-4460-abe6-9bc1609d8c8e.png)

**Comment by WooshiiDev** [comment]
Hi there Razepok, 
I'm back working on this, sorry for the long silence, other work had gotten busy 🙂 

This has been a concern of mine, as previously I had the icons disappear if the width of the window got too small. I removed it as it felt cheap and clunky. 

I have plans to show a stacked script icon of sorts if there's more than one custom script on the instance. Hovering over the script icon will show all the scripts added. This will drastically cut down the horizontal count of icons. 

Overflow can still occur however, and I'm considering adding limits to how many can be shown with priorities. This will come with the next icon settings update however.

For [v0.8.5](https://github.com/WooshiiDev/HierarchyDecorator/tree/v0.8.5), I could add the old functionality back in where it hides the icons if the width becomes too small and then in v0.9 I'll update it to work like I've mentioned above.

Do you have any other thoughts or ideas on this? 

Cheers,
Wooshii

**Comment by Razenpok** [comment]
Hi WooshiiDev,

Stacking the same component icons on top of each other sounds like the best option indeed. I imagine it can be done with a max stack size of 3, and after that number is surpassed, there could be a small plus sign in the corner 🙂

For the time being, adding back the old functionality sounds good to me, as it's still better than obstructed names 😄

You could make it so the hidden icons are shown when the game object is being mouse-over'ed in the hierarchy if you are concerned about components being hidden 🤔 

Thanks!

**Comment by WooshiiDev** [comment]
Hey there Razenpok, 

I took some time to think about this issue and really did not want to rush it. If this is currently an issue with icons, it would no doubt become a problem with all custom drawn GUI's in the hierarchy.

I've went ahead and all [HierarchyInfo](https://github.com/WooshiiDev/HierarchyDecorator/blob/v0.8.5/HierarchyDecorator/Scripts/Editor/Hierarchy/Info/HierarchyInfo.cs) GUIs drawn - this includes the [layers](https://github.com/WooshiiDev/HierarchyDecorator/blob/v0.8.5/HierarchyDecorator/Scripts/Editor/Hierarchy/Info/LayerInfo.cs#L10-L13) and [components](https://github.com/WooshiiDev/HierarchyDecorator/blob/v0.8.5/HierarchyDecorator/Scripts/Editor/Hierarchy/Info/ComponentIconInfo.cs#L149-L152) - to be hidden on a individual basis. This way it's cleaner, provides a nicer experience and doesn't just rip out half of the drawn info when there's an overlap 😅 

I'm going to release v0.8.5 later on today but I've not done so yet just to double check everything is okay to go.
How does this look to you? Anything you'd recommend further?

<p align='center'>
 <img src="https://user-images.githubusercontent.com/31889435/149643497-2c2ff19f-aa43-4be2-84c4-39b52490ed54.gif" alt="Hierarchy Decorator GUI Collapsing Example">
</p>

**Comment by Razenpok** [comment]
Looks good to me! 👍

**Comment by WooshiiDev** [comment]
Hi there, I've released the changes to [v0.8.5](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/v0.8.5)!

I'm going to close the issue as this seems to be a fix for now, but will be considering adding in the hover over too in v0.9.0
If there's any issues with this change please feel free to reply to this issue and I will reopen it if required.
