### ISSUE TITLE
Bug - Extra metadata file package-lock.json.meta

### ISSUE THREAD

**Issue by nolimet** [WooshiiDev/HierarchyDecorator#54]
**Current Unity version used**
2021.2.7f1

**Describe the bug**
There is a extra meta file without a file existing

**To Reproduce (If applicable)**
Clone the repo as version 0.8.4

**Screenshots**
![image](https://user-images.githubusercontent.com/2866064/157128270-49568c97-c235-4300-8dd0-9036a0097161.png)

![image](https://user-images.githubusercontent.com/2866064/157128517-e3a1c26a-f4b5-405c-96b7-ac625f21e199.png)

**Additional context**
This show up every single the the asset data base refreshes .... Please please remove the file as this plugin helps quite a bit with navigating the nightmare that is the fun complex UI prefabs I'm working with

**Comment by WooshiiDev** [comment]
Hi @nolimet,

I'm pretty sure this has been caused due to some problems I caused with the package.json file. Could you try pulling [v0.9.0](https://github.com/WooshiiDev/HierarchyDecorator/tree/v0.9.0) as a fresh packageand let me know if you still have the same issue? 

Thanks,
Wooshii

**Comment by nolimet** [comment]
It to have gone away now. If it resurfaces I will let yea know
