### ISSUE TITLE
Bug - 0.8.5 doesn't show up in OpenUPM

### ISSUE THREAD

**Issue by Razenpok** [WooshiiDev/HierarchyDecorator#56]
As per [Favo Yang](https://github.com/favoyang)

> The problem is that the Git tag is mismatched with package.json version.
> Tag 0.8.5, package.json 0.8.4 [WooshiiDev/HierarchyDecorator@f10ba25/package.json](https://github.com/WooshiiDev/HierarchyDecorator/blob/f10ba2593ca24ffead8e2184c052f24f388c4064/package.json)
> Tag 0.8.4, package.json 0.8.3 [WooshiiDev/HierarchyDecorator@57c0d1b/package.json](https://github.com/WooshiiDev/HierarchyDecorator/blob/57c0d1b1ffff692ccd4095bdbb306a3cfbb0154f/package.json)
> Perhaps your CI could bump package.json version first, then create the Git tag?
> You can align your Git tag and package.json version with 0.8.6 to fix the issue.
> OpenUPM build pipeline section didn't show the actual published version, it just shows the version parsed from the Git tag. Something to improve for us.

https://github.com/openupm/openupm/issues/2927#issuecomment-1104986685

**Comment by WooshiiDev** [comment]
Hi Razen, 

I've just released [v0.8.6](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/v0.8.6) that has a small bug fix for 2021.2+ and have made sure BEFORE making the package the tag is correct.

I see [the build pipelines](https://openupm.com/packages/com.wooshii.hierarchydecorator/?subPage=pipelines) and [versions](https://openupm.com/packages/com.wooshii.hierarchydecorator/?subPage=versions) both showing 0.8.6 correctly.

Could you confirm that it's working correctly for yourself? I'm sorry that I have not been releasing properly so far and making sure versions have been updated.

**Comment by Razenpok** [comment]
Works like a charm now, thank you!
