### ISSUE TITLE
Bug -  PrefabStageUtility class is no longer Experimental

### ISSUE THREAD

**Issue by AtaTrkgl** [WooshiiDev/HierarchyDecorator#57]
**Current Unity version used**
Unity 2021.3.0f1 LTS

**Describe the bug**
The following error is thrown when Unity 2021.3.0f1 LTS version+ is used. This is caused by PrefabStageUtility class no longer being Experimental.
```
Packages\HierarchyDecorator\HierarchyDecorator\Scripts\Editor\Hierarchy\Drawers\ToggleDrawer.cs(47,61): error CS0103: The name 'PrefabStageUtility' does not exist in the current context
```

**Comment by WooshiiDev** [comment]
Did not mean to close this right away @AtaTrkgl 

I have made a new package for [v0.8.6](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/v0.8.6) and added a tag for said version too.

**Comment by AtaTrkgl** [comment]
@WooshiiDev Thank you mate, cheers.
