### ISSUE TITLE
GUIHelper.cs Collides with OdinInspector GUIHelper class. 

### ISSUE THREAD

**Issue by digiwombat** [WooshiiDev/HierarchyDecorator#60]
The asset will fail to compile if the user has Sirenix Odin Inspector installed as the global namespace GUIHelper class collides with HierarchyDecorator's.

**Comment by WooshiiDev** [comment]
Hey there,

thanks so much for finding this, more of my negligence from earlier development that I should have noticed, but has been overlooked 🙁

I've updated the file containing it within the HD namespace as can [be seen here](https://github.com/WooshiiDev/HierarchyDecorator/blob/master/HierarchyDecorator/Scripts/Editor/Util/GUIHelper.cs).

I made a new hotfix release [v0.8.7](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/v0.8.7) that has been pushed to master.

**Comment by digiwombat** [comment]
OpenUPM install is confirmed working great on 2021.3.2f

Thanks for fixing it up! I appreciate all the work you've done on this. Really helps clean up the hierarchy. 😃
