### ISSUE TITLE
Bug - Custom icons do not show immediately

### ISSUE THREAD

**Issue by oliverbooth** [WooshiiDev/HierarchyDecorator#61]
**Current Unity version used**
2021.3.3f1

**Describe the bug**
When disabling `Show All Icons`, adding a new custom icon doesn't take effect until you add another.

**To Reproduce (If applicable)**
- Disable `Show All Icons`
- Add a component in the `Custom` tab
- ???
- Profit

**Screenshots**
![Unity_JfWAILo2fq](https://user-images.githubusercontent.com/1129769/170967538-0cce5e2b-2e89-4e3d-bb98-2a5cc5a2222c.gif)

**Additional context**
I have tried adjusting other settings, like disabling the component icon and re-enabling it again, switching back to `Show All Icons` and back off again, nothing works. The only thing that seems to fix it, is adding a new custom icon - which you then have to delete again because it's not necessary to have a duplicate.

**Comment by WooshiiDev** [comment]
Cheers for reporting this! I probably would not have noticed this for some time 😓 

The checks for custom types do not update the data stored unless the component field was previously null. As I'm [rewriting the settings](https://github.com/WooshiiDev/HierarchyDecorator/tree/feature/new-settings-gui) I'll make sure to note this for upcoming development. 

I've released a new hotfix [v0.8.8](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/v0.8.8) with this fixed.

![hd_custom_icon_switching](https://user-images.githubusercontent.com/31889435/170994932-66ea1033-122c-4394-93da-002eb745c3fa.gif)

**Comment by oliverbooth** [comment]
Seems to work on my end! Thanks for the fix. Fantastic package btw

**Comment by WooshiiDev** [comment]
Issue closed as bug has been confirmed as fixed.
