### ISSUE TITLE
Bug - Prefab children not blue

### ISSUE THREAD

**Issue by pippinmole** [WooshiiDev/HierarchyDecorator#64]
**Current Unity version used**
2021.3.7f1

**Describe the bug**
When inspecting a prefab's children, they are not blue and so it looks like they are not 'applied' to the prefab.

**To Reproduce (If applicable)**
Create a prefab with children, and drag it into a scene. Unfold the prefab to view the children

**Screenshots**
https://sxcu.net/5F9DcZ2XI

As you can see I make a prefab and the children are not blue (blue indicating that the child is applied to said prefab)
Also notice that the child momentarily turns blue when you delete it from the inspector view.

**Comment by WooshiiDev** [comment]
Hey Pippin,

thanks for bringing this to my attention. I know the hierarchy currently has some colour issues when the two-tone background is on.

I want to enhance that feature with custom settings etc, but I'm going to go ahead and fix the selection colours for v0.9 and get the two-tone colours improved in v0.10.

**Comment by WooshiiDev** [comment]
Hi Pippin... 
took way longer than it should have but prefabs are displaying much more accurately to the normal hierarchy with some slight color adjustments.

 - Displaying selection colour
 - Instance label colour varied depending on selection or active state
 - Prefab children/root displaying correct icons.

![image](https://user-images.githubusercontent.com/31889435/219939159-fc400d67-efd8-404b-8b21-c00cf9a509c9.png)

Will push with next release but is currently on [develop](https://github.com/WooshiiDev/HierarchyDecorator/tree/develop).
