### ISSUE TITLE
Bug - GUI style warning is thrown in 2022.3

### ISSUE THREAD

**Issue by oliverbooth** [WooshiiDev/HierarchyDecorator#75]
**Current Unity version used**
2022.3.2f1

**Describe the bug**
This is likely due to a change in the Unity Editor API. HierarchyDecorator attempts to use the style `ToolbarSearchTextField` but Unity 2022.3.2f1 (other versions may also be affected, but this is untested) fails to find it, and a warning is presented. Interestingly, this doesn't affect HD in any other way, and everything else seems to function properly. I guess the fact that it's a warning, not an error, is appropriate.

**To Reproduce (If applicable)**
Use Hierarchy Decorator in 2022.3.2f1 (or any other potentially affected versions)

**Screenshots**
Really, the only screenshot worth showing is of the warning. The full stack trace is provided below.
![image](https://github.com/WooshiiDev/HierarchyDecorator/assets/1129769/4fe96743-9fc7-4465-8a43-294c909a350f)

**Additional context**
The warning shown is as follows:
```cs
Unable to find style 'ToolbarSeachTextField' in skin 'DarkSkin' Layout
UnityEngine.GUIStyle:op_Implicit (string)
HierarchyDecorator.Style:.cctor () (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/Constants.cs:319)
HierarchyDecorator.LayerInfo:DrawInfo (UnityEngine.Rect,UnityEngine.GameObject,HierarchyDecorator.Settings) (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/Hierarchy/Info/LayerInfo.cs:15)
HierarchyDecorator.HierarchyInfo:DrawInternal (UnityEngine.Rect,UnityEngine.GameObject,HierarchyDecorator.Settings) (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/Hierarchy/Info/HierarchyInfo.cs:50)
HierarchyDecorator.HierarchyDrawer:Draw (UnityEngine.Rect,UnityEngine.GameObject,HierarchyDecorator.Settings) (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/Hierarchy/HierarchyDrawer.cs:21)
HierarchyDecorator.HierarchyDecorator:OnHierarchyItem (int,UnityEngine.Rect) (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/HierarchyDecorator.cs:117)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Comment by SnoupS** [comment]
Wrong name, missing the letter R!

ToolbarTextField = new GUIStyle("ToolbarSeachTextField")
ToolbarTextField = new GUIStyle("ToolbarSearchTextField")

**Comment by DamianCobraMobile** [comment]
Thanks for posting this Oliver, I need to look through 2022 and make sure everything is working. Going to get a fix for this with other stuff later today 👍

**Comment by WooshiiDev** [comment]
Thanks for posting this Oliver, I need to look through 2022 and make sure everything is working. Going to get a fix for this with other stuff later today 👍

**Comment by oliverbooth** [comment]
> Wrong name, missing the letter R!
> 
> ToolbarTextField = new GUIStyle("ToolbarSeachTextField") ToolbarTextField = new GUIStyle("ToolbarSearchTextField")

Ah yes good eye. This does seem to be the problem. Weird that this warning was never thrown prior to updating to 2022 🤔

**Comment by tanphat110699** [comment]
![image](https://github.com/WooshiiDev/HierarchyDecorator/assets/57558497/965684a3-7794-4e59-a740-dffe0143d928)
`Unable to find style 'ToolbarSeachTextField' in skin 'DarkSkin' Layout
UnityEngine.GUIStyle:op_Implicit (string)
HierarchyDecorator.Style:.cctor () (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/Constants.cs:319)
HierarchyDecorator.LayerInfo:DrawInfo (UnityEngine.Rect,UnityEngine.GameObject,HierarchyDecorator.Settings) (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/Hierarchy/Info/LayerInfo.cs:15)
HierarchyDecorator.HierarchyInfo:DrawInternal (UnityEngine.Rect,UnityEngine.GameObject,HierarchyDecorator.Settings) (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/Hierarchy/Info/HierarchyInfo.cs:50)
HierarchyDecorator.HierarchyDrawer:Draw (UnityEngine.Rect,UnityEngine.GameObject,HierarchyDecorator.Settings) (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/Hierarchy/HierarchyDrawer.cs:21)
HierarchyDecorator.HierarchyDecorator:OnHierarchyItem (int,UnityEngine.Rect) (at ./Library/PackageCache/com.wooshii.hierarchydecorator@c5d7d76df5/HierarchyDecorator/Scripts/Editor/HierarchyDecorator.cs:117)`
Unity 2022.3.4f1 still have this error. Also the one #77:
![image](https://github.com/WooshiiDev/HierarchyDecorator/assets/57558497/da624486-1ad1-4712-91c5-08035d7b71af)

**Comment by DamianCobraMobile** [comment]
Hi there, 
this should be fixed on both develop and main branches. 
The issue was actually on Unity's side (originally) where they had misspelt the style name, and I had to keep it that way 😭

I've added a check for versions and this should be fixed, could someone confirm?

**Comment by DamianCobraMobile** [comment]
> Also the one #77: 
> ![image](https://user-images.githubusercontent.com/57558497/262672958-da624486-1ad1-4712-91c5-08035d7b71af.png)

This already has an issue created (as you've linked) so I'd keep mentions of it there (so issues dont get messy)

**Comment by WooshiiDev** [comment]
Hi there,
this should be fixed on both develop and main branches.
The issue was actually on Unity's side (originally) where they had misspelt the style name, and I had to keep it that way 😭

I've added a check for versions and this should be fixed, could someone confirm?

**Comment by WooshiiDev** [comment]
> Also the one #77: 
> ![image](https://user-images.githubusercontent.com/57558497/262672958-da624486-1ad1-4712-91c5-08035d7b71af.png)

@tanphat110699 This already has an issue created (as you've linked) so I'd keep mentions of it there (so issues dont get messy)

**Comment by WooshiiDev** [comment]
Closing as fix has been in master for some time
